### PR TITLE
Bruce_Branch request pull

### PR DESCRIPTION
**Pull request by BruceValjean**
Bruce_Branch request pull

### CODE REVIEW

**Comment by evadamtk** [comment]
send to me also

**Comment by matthewstbbs** [comment]
lets colloborate for bruce

**Review by GokhanRepo — COMMENTED** [review]
Comment for Bruce_Branch1's code.

**Review by evadamtk — APPROVED** [review]
good to go

**Review by matthewstbbs — APPROVED** [review]

**Pull request merged**
