### PR TITLE
pullSultan

### PR DESCRIPTION
**Pull request by sultanorbay**

### CODE REVIEW

**Review by veys66 — APPROVED** [review]

**Review by matthewstbbs — APPROVED** [review]
good

**Review by GokhanRepo — CHANGES_REQUESTED** [review]
Look Ok, Sultan

**Review by evadamtk — COMMENTED** [review]
what was the subject, primitive types casting?

**Review by GokhanRepo — COMMENTED** [review]
Now, I can write only a review without other options.

**Comment by GokhanRepo** [comment]
comment by IJ

**Pull request merged**
