### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BruceValjean**
I updated read me file. Enjoy !

I also could update the top comment by Bruce! This is Gokhan.

### CODE REVIEW

**Review by GokhanRepo — COMMENTED** [review]
I agree with you!

HOW CAN I EDIT YOUR COMMENT Gokhan? This is Matt.

**Comment by matthewstbbs** [comment]
we cannot merge and forced for a single branch friends.
have we broken our toy?

**Comment by GokhanRepo** [comment]
Can you create your branch from the master?

> we cannot review, aprove and merge and forced for a single branch friends.
> 
> have we broken our toy?

**Review by Bahartaskin — APPROVED** [review]

**Review by evadamtk — APPROVED** [review]
good enough, anything else do you want me to do?

**Comment by GokhanRepo** [comment]
Did a Rebase and Merge in the PR menu of the IJ. then PR is merged.

**Review by evadamtk — COMMENTED** [review]
it is good

**Pull request merged**
