### PR TITLE
Pull request for Gokhan_branch6

### PR DESCRIPTION
**Pull request by GokhanRepo**
1. Added codes.
2. Fixed something

### CODE REVIEW

**Review by matthewstbbs — CHANGES_REQUESTED** [review]
testing merge in the case of "request change".

**Review by Zehradrc — APPROVED** [review]

**Comment by Zehradrc** [comment]
good job

**Review by veys66 — APPROVED** [review]

**Review by matthewstbbs — APPROVED** [review]

**Review by GulsumOztomsuk — APPROVED** [review]

**Review by evadamtk — APPROVED** [review]
it is also ok for me

**Comment by sultanorbay** [comment]
unfinished

**Comment by GokhanRepo** [comment]
I confirmed squash and merged

**Review by evadamtk — COMMENTED** [review]
it is ok

**Pull request merged**
